# Generated by Django 3.0.5 on 2020-05-05 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200504_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.ProjectSection'),
        ),
    ]
