# Generated by Django 3.0.5 on 2020-05-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200504_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background',
            field=models.CharField(default='#000', max_length=50),
            preserve_default=False,
        ),
    ]
