# Generated by Django 3.0.5 on 2020-05-06 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_project_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owneer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
