# Generated by Django 3.0.5 on 2020-05-06 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_project_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owneer',
            new_name='owner',
        ),
    ]
