# Generated by Django 3.0.5 on 2020-05-10 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200506_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_section',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 10, 13, 31, 45, 337929)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.Task')),
            ],
        ),
        migrations.CreateModel(
            name='SectionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='tasks.ProjectSection')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tasks.Project')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='section_list',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.SectionList'),
            preserve_default=False,
        ),
    ]
