# Generated by Django 3.0.5 on 2020-05-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200510_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionlist',
            name='position',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
