# Generated by Django 3.0.5 on 2020-05-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20200510_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProjectMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('project', models.ManyToManyField(to='tasks.Project')),
            ],
        ),
    ]
