# Generated by Django 3.0.5 on 2020-05-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_userprojectmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprojectmapping',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userprojectmapping',
            name='username',
            field=models.CharField(default='deleted', max_length=150),
            preserve_default=False,
        ),
    ]
